apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
  labels:
    name: hello
    {{- template "labels" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: hello
        image: {{ .Values.greeting.image }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.internalPort }}
          name: "http"
        - containerPort: {{ .Values.service.internalDebugPort }}
          name: "debug"
